# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Quarkus Native Deployment

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'

      - name: Build Quarkus Native
        run: mvn clean package -Pnative -DskipTests

      - name: Move Native Image
        run: |
          sudo mkdir -p /opt/quarkus
          sudo mv target/*-runner /opt/quarkus/

      - name: Configure Systemd
        run: |
          sudo tee /etc/systemd/system/quarkus-native.service > /dev/null <<EOT
          [Unit]
          Description=Quarkus Native Service
          After=network.target

          [Service]
          ExecStart=/opt/quarkus/*-runner
          Restart=always
          User=$USER
          Group=$USER

          [Install]
          WantedBy=multi-user.target
          EOT

          sudo systemctl daemon-reload

      - name: Start Quarkus Service
        run: |
          sudo systemctl enable quarkus-native
          sudo systemctl start quarkus-native
  
